[package]
name = "pixpox_ecs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
queues = "1.0.2"
bit-set = "0.5.3"
bit-vec = "0.6.3"