[package]
name = "sandbox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixelox = { path = "../pixelox", version = "0.1.0" }
winit = "0.26"
env_logger = "0.9"
log = "0.4"
wgpu = "0.13"